### PR TITLE
Update content.js

### PR DESCRIPTION
**Pull request by koMah**
Showing drag cursor

### CODE REVIEW

**Comment by davidparsson** [comment]
Thanks! This should fix #31.

**Comment by davidparsson** [comment]
`-moz-grabbing` is obviously not needed since this is a Chrome only plugin, but it's all right.

**Comment by koMah** [comment]
Ahahahah my crossbrowser obsession XD

**Comment by davidparsson** [comment]
In most cases it's a good habit. :) The new version is being published right now.

**Pull request merged**
